In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn

In [81]:
class CNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        super(CNN, self).__init__()
        self.vocab_size = vocab_size
        self.embedding_dim = embedding_dim
        
        # layers
        self.embedding = nn.Embedding(self.vocab_size, self.embedding_dim)
        self.conv1 = nn.Conv1d(126,126,kernel_size=(5))
        self.conv2 = nn.Conv1d(126,1,kernel_size=(5))
#         self.conv3 = nn.Conv1d(1,1,kernel_size=(5))
        self.max1 = nn.MaxPool1d(5)
#         self.max2 = nn.MaxPool1d(35)
        self.fc = nn.Linear(8460,2)
        self.softmax = nn.Softmax()
    
    def forward(self, x):
        x = self.embedding(x)
        x = self.conv1(x)
        x = self.max1(x)
        x = self.conv2(x)
        x = self.fc(x.flatten())
        print(x)
        x = self.softmax(x)
        print(x)
        return x

In [82]:
model = CNN(76,100)

In [83]:
labels = ['sarkas','non sarkas']
inputs = torch.randn(564,126)
inputs = inputs.random_(0,2)
print(inputs)
pred = model(inputs.long())
pred = torch.max(pred,0)[1]
labels[pred]

tensor([[0., 0., 1.,  ..., 1., 1., 1.],
        [0., 0., 1.,  ..., 1., 1., 0.],
        [0., 0., 1.,  ..., 1., 0., 1.],
        ...,
        [0., 0., 1.,  ..., 1., 1., 0.],
        [1., 1., 1.,  ..., 1., 1., 0.],
        [1., 0., 1.,  ..., 1., 0., 0.]])
tensor([-0.0117,  1.0560], grad_fn=<ThAddBackward>)
tensor([0.2558, 0.7442], grad_fn=<SoftmaxBackward>)


E:\Program\Anaconda\lib\site-packages\ipykernel_launcher.py:24: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


'non sarkas'

In [38]:
torch.max(pred,0)[1]

tensor(0)

In [39]:
labels = ['sarkas','non sarkas']

In [40]:
labels[torch.max(pred,0)[1]]

'sarkas'

In [53]:
s = torch.rand(4,4)
s.shape

torch.Size([4, 4])

In [55]:
s.flatten().shape

torch.Size([16])